apiVersion: ctlptl.dev/v1alpha1
kind: Cluster
name: myproj
product: minikube
registry: myproj-reg
minikube:
  startFlags:
    - "--addons=ingress,ingress-dns"
    - "--nodes=1"

---
# Creates a registry available on 127.0.0.1:5001
apiVersion: ctlptl.dev/v1alpha1
kind: Registry
port: 5001
name: myproj-reg
listenAddress: 127.0.0.1
